# -*- coding: utf-8 -*-
"""Anova1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppS_IFrvFxVkKnLx5oniPeE55d0Zv8It
"""

#One Way Anova
#!pip install scipy numpy matplotlib
# Import Libraries
import numpy as np
from scipy.stats import f_oneway
import matplotlib.pyplot as plt
#Create Student Marks Data
# Marks of 3 classes
class_A = [75, 80, 85, 90, 95]
class_B = [70, 72, 78, 74, 76]
class_C = [88, 85, 91, 89, 87]
print("Class A:", class_A)
print("Class B:", class_B)
print("Class C:", class_C)
#Perform ANOVA Test
# ANOVA Test
f_statistic, p_value = f_oneway(
    class_A,
    class_B,
    class_C
)
print("F-Statistic:", f_statistic)
print("P-Value:", p_value)
# Interpretation
if p_value < 0.05:
    print("Significant difference exists between groups")
else:
    print("No significant difference between groups")
# Visualization
# Boxplot visualization
data = [class_A, class_B, class_C]
plt.boxplot(data)
plt.title("ANOVA Analysis")
plt.xlabel("Classes")
plt.ylabel("Marks")
plt.show()